name: Debug Sync
on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Show Remotes
      run: |
        git remote add test https://${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git
        git ls-remote test
        git remote remove test
