- name: Test Access
  run: |
    # Test read access
    curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
         https://api.github.com/repos/oterdimanx/reference-web-966b2c83
    
    # Test write access
    curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
         https://api.github.com/repos/oterdimanx/reference-web-966b2c83/issues \
         -d '{"title":"Test"}'
