name: Sync Repositories

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Safe Sync
      run: |
        git fetch origin
        git push --force-with-lease mirror main:main
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
