name: Sync Repositories
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add Authenticated Remote
      run: |
        git remote add mirror "https://${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git"
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Verify Remote Access
      run: git ls-remote mirror

    - name: Push Changes
      run: git push mirror HEAD:main
