name: Secure Public Repo Sync
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Debug Home Directory
        run: |
          ls -al $HOME
          ls -al $HOME/.gitconfig || echo "No .gitconfig"

      - name: Configure Minimal Git Identity (local)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --unset-all http.https://github.com/.extraheader || true

      - name: Add PAT-authenticated Remote
        run: |
          git remote add mirror "https://${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git"

      - name: Fetch All Branches
        run: git fetch --all

      - name: Push Changes to Mirror Remote
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git push mirror $BRANCH:$BRANCH --force
