name: Secure Public Repo Sync
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false  # Critical for public repos

    - name: Configure Minimal Git Identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add PAT-authenticated Remote
      run: |
        git remote add mirror "https://${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git"

    - name: Verify Remote Access
      run: git ls-remote mirror

    - name: Push Changes
      run: git push -u origin master
