name: Secure Sync
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # SECRET VALIDATION STEP HERE
    - name: Validate PAT Secret
      run: |
        echo "PAT exists: ${#GH_PAT}"  # Should output "PAT exists: 40"
        echo "First 5 chars: ${GH_PAT:0:5}"  # Partial verification

    - name: Configure Authenticated Remote
      run: |
        git remote add mirror "https://x-access-token:${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git"
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Test Connection
      run: git ls-remote mirror

    - name: Push Changes
      run: git push --force-with-lease mirror HEAD:main
