name: Private Repo Sync
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Critical for full history

    - name: Configure Authentication
      run: |
        # Encode PAT for Git operations
        echo "machine github.com" > ~/.netrc
        echo "login x" >> ~/.netrc
        echo "password ${{ secrets.GH_PAT }}" >> ~/.netrc
        chmod 600 ~/.netrc

    - name: Add Target Remote
      run: |
        git remote add mirror https://github.com/oterdimanx/reference-web.git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Debug Verification
      run: |
        git ls-remote mirror
        git remote -v
        git branch --all

    - name: Force Push
      run: |
        git push --force-with-lease mirror HEAD:main
