name: Safe Repository Sync
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history

    - name: Configure Mirror Remote
      run: |
        # Remove existing remote if present
        git remote remove mirror || true
        
        # Add remote with authentication
        git remote add mirror https://${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git
        
        # Verify remote
        git remote -v

    - name: Push to Mirror
      run: |
        git push mirror HEAD:main
