name: Safe Mirror Sync
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure Mirror (PAT in URL Only)
      run: |
        git remote add mirror "https://${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git"
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Test Connection
      run: git ls-remote mirror

    - name: Push Changes
      run: git push --force-with-lease mirror HEAD:main
