name: Sync to Private Repo
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for full history

    - name: Configure Mirror
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote add mirror "https://${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git"
        git remote -v  # Verify remote configuration

    - name: Push to Mirror
      run: |
        git push --force-with-lease mirror HEAD:main
