name: Secure Sync
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure Authenticated Remote
      run: |
        # Use GitHub's recommended PAT format
        git remote add mirror "https://x-access-token:${{ secrets.GH_PAT }}@github.com/oterdimanx/reference-web.git"
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Test Connection
      run: git ls-remote mirror

    - name: Push Changes
      run: git push --force-with-lease mirror HEAD:main
